site_name: Tech Radar
site_description: TROi technology choices — Adopt, Trial, Assess, Hold
site_author: Christoffer Råsten
repo_url: https://github.com/ChrickeR/tech-radar
site_url: https://tech-radar.troi.se/

theme:
  name: material
  features:
    - navigation.instant
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

nav:
  - Overview: index.md
  - Blips:
      - TypeScript (React Native): blips/typescript-react-native.md
      - Expo: blips/expo.md
      - React Navigation: blips/react-navigation.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - toc:
      permalink: true
